spring.application.name=cubitor


spring.datasource.url=jdbc:mysql://45.154.117.12:3306/cubitor?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=cubitor_user
spring.datasource.password=UpYbdPs5dc05sirn
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
